"""create all tabless

Revision ID: 34c20b2195da
Revises: 335891da4d72
Create Date: 2024-11-22 18:51:23.719527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c20b2195da'
down_revision: Union[str, None] = '335891da4d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Moderators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_Moderators_id'), 'Moderators', ['id'], unique=False)
    op.add_column('Applications', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('Categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('Categories', 'active_duration')
    op.add_column('Clients', sa.Column('password', sa.String(), nullable=False))
    op.add_column('Customer', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('Customer', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('Customer_phone_num_key', 'Customer', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Customer_phone_num_key', 'Customer', ['phone_num'])
    op.drop_column('Customer', 'is_active')
    op.drop_column('Customer', 'is_verified')
    op.drop_column('Clients', 'password')
    op.add_column('Categories', sa.Column('active_duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Categories', 'is_active')
    op.drop_column('Applications', 'is_active')
    op.drop_index(op.f('ix_Moderators_id'), table_name='Moderators')
    op.drop_table('Moderators')
    # ### end Alembic commands ###
